name: Release

on:
  workflow_dispatch:
    inputs:
      bump:
        type: choice
        description: Semver version to bump
        options:
          - patch
          - minor
          - major
        default: patch
      dry-run:
        type: string
        description: Perform dry-run
        default: 'true'

defaults:
  run:
    shell: bash

permissions:
  contents: write
  id-token: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm install -g npm
      - name: git config
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
      - run: npm install
      - run: release-it ${{ github.event.inputs.bump }} -VV ${{ github.event.inputs.dry-run == 'true' && '--dry-run' || '' }}
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
